steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/app1-417719/dock/image2', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/app1-417719/dock/image2' ]
    
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', './kubernetes/pvc.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', './kubernetes/deployment.yaml' ]
    env:
      # - 'BUILD_ID=$BUILD_ID'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', './kubernetes/service.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'